services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production-build
      args:
        API_DOMAIN: ${API_DOMAIN}
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/certs
      - /app/schemas
      - /app/dist
    command: node /app/dist/main.js -i -1
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      kafka:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - KAFKA_BROKERS=kafka:9095
      - KAFKA_SSL_ENABLED=true
      - KAFKA_SSL_REJECT_UNAUTHORIZED=false
      - KAFKA_SSL_CA=${KAFKA_SSL_CA}
      - KAFKA_SSL_CERT=${KAFKA_SSL_CERT}
      - KAFKA_SSL_KEY=${KAFKA_SSL_KEY}
      - KAFKA_SASL_MECHANISM=PLAIN
      - KAFKA_SASL_USERNAME=kafka_user
      - KAFKA_SASL_PASSWORD=kafka_password
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    restart: always
    healthcheck:
      test: ["CMD", "bash", "-lc", "clickhouse-client --query 'SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-kafka-auth-config-example/clickhouse-ssl-sasl.xml:/etc/clickhouse-server/config.d/kafka.xml:ro
      - ./certs:/opt/bitnami/kafka/config/certs:ro
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - app-network
  kafka:
    image: bitnamilegacy/kafka:3.7.0
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
      - 9095:9095
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,SASL_SSL://:9095,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,SASL_SSL://kafka:9095,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_SSL:SASL_SSL,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=server_keystore_password
      - KAFKA_CFG_SSL_KEY_PASSWORD=server_keystore_password
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=server_truststore_password
      - KAFKA_CFG_SSL_CLIENT_AUTH=required
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka_user" password="kafka_password" user_kafka_user="kafka_password" user_admin="admin_password";
      - KAFKA_CFG_LISTENER_NAME_SASL_SSL_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_LISTENER_NAME_SASL_SSL_PLAIN_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka_user" password="kafka_password" user_kafka_user="kafka_password" user_admin="admin_password";
    volumes:
      - kafka-data:/bitnami/kafka
      - ./certs:/opt/bitnami/kafka/config/certs:ro
    healthcheck:
      test: ["CMD", "bash", "-lc", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60
    networks:
      - app-network
volumes:
  clickhouse-data:
  kafka-data:
networks:
  app-network:
